#!/usr/bin/env python3
"""Write one live source per Florida OpenGov tenant, from the platform's directory.

OpenGov is the rare platform that publishes its own tenant census: every
government using it, with state and active flag, unauthenticated. So the
Florida source list is not curated — it is *derived*, and an agency that
migrates onto the platform shows up here the week it does.

The counterpart of that is a standing obligation to re-run this. Three Florida
migrations were observed inside a single week of research; a list written once
is out of date by the next quarter.

Usage::

    python scripts/discover_opengov_tenants.py                  # write the config
    python scripts/discover_opengov_tenants.py --check          # diff only, no write
    python scripts/discover_opengov_tenants.py --probe          # verify each tenant answers
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Set

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.fl_geo import COUNTY_NAMES, infer_county  # noqa: E402
from src.sources.opengov import OpenGovAdapter, fl_tenants  # noqa: E402

OUT = Path("config/sources.opengov.yaml")
EXISTING = Path("config/sources.yaml")

HEADER = (
    "# Florida OpenGov Procurement tenants — GENERATED by\n"
    "# scripts/discover_opengov_tenants.py. Do not hand-edit: rerun the script.\n"
    "#\n"
    "# Sourced from the platform's own public directory\n"
    "# (GET https://api.procurement.opengov.com/api/v1/government, state == FL\n"
    "# and isActive), so new tenants appear on a re-run. Weekly is enough.\n"
    "#\n"
    "# Note the two hosts: the portal these URLs point at is Cloudflare-fronted\n"
    "# and 403s a scraper, while the API the adapter actually calls is open.\n"
    "# portal_url is for a human to click, not for the adapter to fetch.\n"
)


def entries(tenants: List[Dict[str, str]]) -> List[Dict]:
    out: List[Dict] = []
    for t in tenants:
        name, code = t["name"], t["code"]
        out.append(
            {
                "id": f"og_{code}",
                "name": f"{name} (OpenGov)",
                "county": infer_county(name, hint=None) or "unknown",
                "agency": name,
                "live_fetch": True,
                "adapter": "opengov",
                "platform": "opengov",
                "opengov_code": code,
                "portal_url": f"https://procurement.opengov.com/portal/{code}",
            }
        )
    return out


def known_ids(path: Path) -> Set[str]:
    if not path.exists():
        return set()
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {s.get("id", "") for s in (data.get("sources") or []) if isinstance(s, dict)}


def probe(rows: List[Dict]) -> None:
    """Confirm each tenant answers the public project endpoint. Slow; opt-in."""
    ok = empty = failed = 0
    for row in rows:
        adapter = OpenGovAdapter(dict(row, id=row["id"], name=row["name"]))
        try:
            found = len(adapter.fetch())
        except Exception as e:  # noqa: BLE001 — a probe report, not a pipeline
            failed += 1
            print(f"  FAIL {row['opengov_code']:<28} {type(e).__name__}: {e}")
            continue
        if found:
            ok += 1
            print(f"  ok   {row['opengov_code']:<28} {found} open")
        else:
            empty += 1
            print(f"  ---  {row['opengov_code']:<28} 0 open")
    print(f"\nprobe: {ok} with open bids, {empty} empty, {failed} failed")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="report changes, write nothing")
    ap.add_argument("--probe", action="store_true", help="fetch each tenant to verify it responds")
    args = ap.parse_args()

    tenants = fl_tenants()
    print(f"OpenGov directory: {len(tenants)} active Florida tenants")

    rows = entries(tenants)
    already = known_ids(EXISTING)
    rows = [r for r in rows if r["id"] not in already]

    previous = known_ids(args.out)
    added = [r["id"] for r in rows if r["id"] not in previous]
    removed = sorted(previous - {r["id"] for r in rows})
    if added:
        print(f"  new tenants: {', '.join(added)}")
    if removed:
        print(f"  gone from the directory: {', '.join(removed)}")
    if not added and not removed:
        print("  no change since the last run")

    if args.probe:
        probe(rows)

    if args.check:
        return 1 if (added or removed) else 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + yaml.safe_dump({"sources": rows}, sort_keys=False, width=100),
        encoding="utf-8",
    )
    counties = {r["county"] for r in rows if r["county"] in COUNTY_NAMES}
    print(f"\nWrote {len(rows)} sources to {args.out}")
    print(f"  counties represented: {len(counties)}/67")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
