#!/usr/bin/env python3
"""Read VendorLink's agency dropdown and configure the Florida ones.

The platform publishes its whole tenant directory as a `<select>` on any
agency's public page, so the source list is derived rather than curated.

The directory is not Florida-only, which is the trap. It carries Cape Hatteras
Electric Cooperative (North Carolina), City of Murfreesboro (Tennessee), Coast
Electric Power Association (Mississippi) and EducationPlus (Missouri) alongside
the Florida agencies — the same lesson the Bonfire sweep learned when `nsu`
turned out to be Norfolk State and `tsc` Texas Southmost College.

Name matching alone cannot settle it in either direction. `infer_county` places
79 of the 114 entries in a Florida county, but among the 35 it cannot place are
City of Mascotte and City of Umatilla, which are both in Lake County. So this
script does not decide: confident matches are written to config, and everything
else is printed for a human to look at once. Guessing would either drop real
coverage or quietly configure another state's utility co-op.

Usage::

    python scripts/discover_vendorlink.py --check     # report, write nothing
    python scripts/discover_vendorlink.py             # write the config
    python scripts/discover_vendorlink.py --probe     # fetch each one first
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.fl_geo import COUNTY_NAMES, infer_county  # noqa: E402
from src.sources.vendorlink import BIDS, VendorLinkAdapter  # noqa: E402

OUT = Path("config/sources.vendorlink.yaml")

#: A seed agency whose page carries the dropdown. Any id works; Brevard is
#: large and stable.
SEED_AGENCY = 70

#: Names that say Florida outright even when no county can be inferred.
_FLORIDA_HINT = re.compile(r"\bflorida\b|\bfl\b|\bfla\b", re.I)

#: Names that say some *other* state outright. This has to be checked before
#: county inference, not after: 23 Florida counties share a name with a city or
#: county elsewhere, so "City of Madison, Georgia" infers cleanly to Madison
#: County, Florida and would be configured as a Florida agency on the strength
#: of the word it shares with one.
_OTHER_STATE = re.compile(
    r",\s*(?:alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|"
    r"georgia|hawaii|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|"
    r"maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|"
    r"nevada|new hampshire|new jersey|new mexico|new york|north carolina|north dakota|"
    r"ohio|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|"
    r"tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming)\b"
    r"|\b(?:alabama|georgia|indiana|mississippi|missouri|tennessee|north carolina)\s+"
    r"(?:sheriffs|association|electric|power)\b",
    re.I,
)

HEADER = (
    "# VendorLink Florida agencies — GENERATED by scripts/discover_vendorlink.py.\n"
    "# Do not hand-edit: rerun the script.\n"
    "#\n"
    "# Sourced from the platform's own agency dropdown. The directory is not\n"
    "# Florida-only, so entries whose state could not be established are left\n"
    "# out and reported by the script rather than guessed at.\n"
    "#\n"
    "# Detail pages are login-gated, so these are list-only: reference number,\n"
    "# both deadlines, status and the pre-bid flag, but no documents.\n"
)


def classify(directory: Dict[str, str]) -> Tuple[List[Dict], List[Tuple[str, str]]]:
    """(configurable sources, entries needing a human)."""
    sources: List[Dict] = []
    unresolved: List[Tuple[str, str]] = []

    for agency_id, name in sorted(directory.items(), key=lambda kv: kv[1].lower()):
        if _OTHER_STATE.search(name):
            unresolved.append((agency_id, f"{name}  [names another state]"))
            continue

        county = infer_county(name)
        confident = county in COUNTY_NAMES or county == "statewide" or _FLORIDA_HINT.search(name)
        if not confident:
            unresolved.append((agency_id, name))
            continue
        sources.append(
            {
                "id": f"vl_{agency_id}",
                "name": f"{name} (VendorLink)",
                "county": county if county in COUNTY_NAMES else "statewide",
                "agency": name,
                "live_fetch": True,
                "adapter": "vendorlink",
                "platform": "vendorlink",
                "vendorlink_agency": int(agency_id),
                "portal_url": f"{BIDS}?a={agency_id}",
            }
        )
    return sources, unresolved


def probe(sources: List[Dict]) -> List[Dict]:
    """Keep the agencies whose board actually answers."""
    kept: List[Dict] = []
    for cfg in sources:
        adapter = VendorLinkAdapter(cfg)
        try:
            found = len(adapter.fetch())
        except Exception as e:  # noqa: BLE001 — a probe report, not a pipeline
            print(f"  drop {cfg['id']:<10} {cfg['agency'][:40]:<42} {type(e).__name__}")
            continue
        note = adapter.degraded_reason or ""
        if "grid was not found" in note:
            # The agency is in the dropdown but serves no board — usually one
            # that has moved off the platform and left its entry behind.
            # Configuring it would report a permanently degraded source rather
            # than an absent one, which is worse than not configuring it.
            print(f"  drop {cfg['id']:<10} {cfg['agency'][:40]:<42} no grid on the page")
            continue
        print(f"  ok   {cfg['id']:<10} {cfg['agency'][:40]:<42} {found} open {note}")
        kept.append(cfg)
    return kept


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--probe", action="store_true", help="fetch each agency before writing")
    ap.add_argument("--seed", type=int, default=SEED_AGENCY)
    args = ap.parse_args()

    seed_cfg = {
        "id": "vl_seed",
        "name": "VendorLink directory probe",
        "county": "statewide",
        "agency": "VendorLink",
        "portal_url": f"{BIDS}?a={args.seed}",
        "vendorlink_agency": args.seed,
    }
    directory = VendorLinkAdapter(seed_cfg).agencies()
    print(f"VendorLink directory: {len(directory)} agencies")
    if not directory:
        print("  the agency dropdown was not found — the page layout may have changed")
        return 1

    sources, unresolved = classify(directory)
    print(f"  confidently Florida: {len(sources)}")
    print(f"  state not established: {len(unresolved)} (left out — review these by hand)")
    for agency_id, name in unresolved:
        print(f"    {agency_id:>5}  {name[:60]}")

    if args.probe and sources:
        print("\nprobing:")
        sources = probe(sources)
        print(f"  {len(sources)} answered")

    if args.check:
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + yaml.safe_dump({"sources": sources}, sort_keys=False, width=100),
        encoding="utf-8",
    )
    counties = {s["county"] for s in sources if s["county"] in COUNTY_NAMES}
    print(f"\nWrote {len(sources)} sources to {args.out}")
    print(f"  counties represented: {len(counties)}/67")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
