#!/usr/bin/env python3
"""Turn the verified source registry into live config, for adapters we have.

`data/registry/fl_procurement_sources.csv` is the research deliverable: 133
agency → platform → adapter mappings, each confirmed live on 6 Aug 2026. It is
the *input*, not the code — the point of §4 of the handoff is that source rows
are derived from it rather than hand-written.

This script reads that registry and emits `config/sources.registry.yaml` for
every row whose platform we can actually fetch today. Rows whose platform has no
adapter are counted and reported, never silently dropped: the gap between "133
sources verified" and "N sources fetched" is the number that matters, and it
should be visible without reading code.

Two platforms are handled specially:

* **OpenGov** already has a generated file of its own, derived from the
  platform's live directory (`scripts/discover_opengov_tenants.py`). That
  directory is fresher than any CSV, so the registry's 91 rows are skipped here.
  The two lists were compared and are identical, which is a good sign for both.
* **Bonfire** tenants are matched on subdomain against what is already
  configured, so re-running adds only what is genuinely new.

Usage::

    python scripts/seed_from_registry.py            # write the config
    python scripts/seed_from_registry.py --check    # report, write nothing
    python scripts/seed_from_registry.py --probe    # fetch each new source first
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.fl_geo import COUNTY_NAMES, infer_county  # noqa: E402
from src.sources.registry import ADAPTERS  # noqa: E402

REGISTRY = Path("data/registry/fl_procurement_sources.csv")
OUT = Path("config/sources.registry.yaml")

#: Registry adapter name -> the adapter this repo actually ships. The research
#: named platforms from the outside; the repo named them as they were built.
ADAPTER_ALIASES = {"vip": "mfmp_vbs", "flsheriffs_rss": "fsa_rss"}

#: Handled by a fresher, platform-native discovery path.
SKIP_PLATFORMS = {"opengov"}

HEADER = (
    "# Florida sources seeded from the verified research registry — GENERATED by\n"
    "# scripts/seed_from_registry.py. Do not hand-edit: rerun the script.\n"
    "#\n"
    "# Source of truth: data/registry/fl_procurement_sources.csv (133 rows, each\n"
    "# confirmed live 2026-08-06). Only rows whose platform this build has an\n"
    "# adapter for appear here; the rest are reported by the script as the\n"
    "# outstanding coverage gap.\n"
    "#\n"
    "# OpenGov is deliberately absent — config/sources.opengov.yaml is derived\n"
    "# from the platform's own live directory, which is fresher than the CSV.\n"
)


def bonfire_slug(url: str) -> str | None:
    m = re.search(r"https?://([a-z0-9-]+)\.bonfirehub\.com", url or "")
    return m.group(1) if m else None


def configured(exclude: Path) -> tuple[set, set]:
    """Bonfire subdomains and source ids already covered by config.

    `exclude` is this script's own output, and leaving it in is a trap: the
    second run reads last run's file, concludes every source in it is "already
    configured", and rewrites the file without them. A generator must never
    count its own output as prior art.
    """
    cfg_dir = Path("config")
    paths = [p for p in sorted(cfg_dir.glob("sources*.yaml")) if p.resolve() != exclude.resolve()]

    cfg: List[Dict] = []
    for p in paths:
        data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        cfg += [c for c in (data.get("sources") or []) if isinstance(c, dict)]

    slugs = {str(c["bonfire_host"]).split(".")[0] for c in cfg if c.get("bonfire_host")}
    return slugs, {c.get("id") for c in cfg}


def build(rows: List[Dict], out_path: Path) -> tuple[List[Dict], Counter]:
    have_slugs, have_ids = configured(out_path)
    fresh: List[Dict] = []
    skipped: Counter = Counter()

    for r in rows:
        platform = r["platform"]
        if platform in SKIP_PLATFORMS:
            skipped[f"{platform} (covered by native discovery)"] += 1
            continue

        adapter = ADAPTER_ALIASES.get(r["adapter"], r["adapter"])
        if adapter not in ADAPTERS:
            skipped[f"{platform} (no {adapter} adapter)"] += 1
            continue

        if platform != "bonfire":
            # Everything else in the registry is a single statewide feed this
            # repo already configures by hand; re-emitting would duplicate it.
            skipped[f"{platform} (already configured by hand)"] += 1
            continue

        slug = bonfire_slug(r["portal_url"])
        if not slug:
            skipped["bonfire (no subdomain in portal_url)"] += 1
            continue
        if slug in have_slugs:
            skipped["bonfire (already configured)"] += 1
            continue

        name = r["name"]
        sid = f"bf_{slug.replace('-', '_')}"
        if sid in have_ids:
            skipped["id collision"] += 1
            continue

        fresh.append(
            {
                "id": sid,
                "name": f"{name} (Bonfire)",
                "county": r["county"] if r["county"] in COUNTY_NAMES else infer_county(name),
                "agency": name,
                "live_fetch": True,
                "adapter": "bonfire",
                "platform": "bonfire",
                "bonfire_host": f"{slug}.bonfirehub.com",
                "portal_url": f"https://{slug}.bonfirehub.com/portal/?tab=openOpportunities",
            }
        )
    return fresh, skipped


def probe(rows: List[Dict]) -> List[Dict]:
    """Fetch each candidate, keeping only the ones that answer.

    Bonfire returns ``success: 0`` both for a portal generation we cannot read
    *and* when it is rate-limiting, so a single failed probe is not proof a
    tenant is unreadable — pace the calls and retry once before believing it.
    """
    import time

    from src.sources.bonfire import BonfireAdapter

    kept: List[Dict] = []
    for row in rows:
        ok = False
        for attempt in (1, 2):
            try:
                found = len(BonfireAdapter(row).fetch())
                print(f"  ok   {row['bonfire_host']:<34} {found} open")
                ok = True
                break
            except Exception as e:  # noqa: BLE001 — this is a probe report
                if attempt == 2:
                    print(f"  drop {row['bonfire_host']:<34} {str(e)[:60]}")
            time.sleep(3)
        if ok:
            kept.append(row)
        time.sleep(1.5)
    return kept


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--registry", type=Path, default=REGISTRY)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--probe", action="store_true", help="fetch each new source first")
    args = ap.parse_args()

    if not args.registry.exists():
        print(f"registry not found: {args.registry}", file=sys.stderr)
        return 2

    rows = list(csv.DictReader(args.registry.open(encoding="utf-8")))
    print(f"registry: {len(rows)} verified sources")

    fresh, skipped = build(rows, args.out)
    print(f"new sources this build can fetch: {len(fresh)}")
    for reason, n in sorted(skipped.items(), key=lambda kv: -kv[1]):
        print(f"  skipped {n:>3}  {reason}")

    if args.probe and fresh:
        print("\nprobing:")
        fresh = probe(fresh)
        print(f"  {len(fresh)} answered")

    if args.check:
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + yaml.safe_dump({"sources": fresh}, sort_keys=False, width=100),
        encoding="utf-8",
    )
    print(f"\nWrote {len(fresh)} sources to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
