#!/usr/bin/env python3
"""Turn fingerprint results into configured sources, for platforms we can fetch.

`scripts/fingerprint_agencies.py` answers "what does this agency run?".
This answers "so what?" — it takes the strong matches on platforms this build
has an adapter for and writes them as live sources.

Kept separate from the sweep on purpose. Discovering that a city runs CivicPlus
and deciding to crawl it every day are different decisions, and the second one
should be reviewable: this writes one generated file, prints what it skipped
and why, and can be re-run without touching anything a human tuned by hand.

Three rules the output depends on:

* **Strong matches only.** A weak fingerprint means the platform's name appeared
  in prose — usually "go register over there" — which is a lead, not a tenant.
  Configuring one would invent coverage.
* **Probe before configuring.** A signature on a page is not proof the adapter
  can read the board. Every candidate is fetched once, and only the ones that
  answer are written. This is where the CivicPlus pointer pages fall out.
* **Never shadow an existing source.** Anything already configured by hand or by
  another generator wins, matched on both source id and portal host.

Usage::

    python scripts/sources_from_fingerprints.py --check     # report only
    python scripts/sources_from_fingerprints.py             # write the config
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional
from urllib.parse import urlsplit

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.fl_geo import COUNTY_NAMES, infer_county  # noqa: E402

FINGERPRINTS = Path("data/registry/fingerprints.jsonl")
OUT = Path("config/sources.fingerprinted.yaml")
CONFIG_DIR = Path("config")

#: Fingerprint platform -> the adapter that reads it. Only platforms in this
#: map can become sources; everything else is reported as an outstanding gap.
PLATFORM_ADAPTERS = {
    "civicplus": "civicplus",
    "bonfire": "bonfire",
    "opengov": "opengov",
}

HEADER = (
    "# Florida sources discovered by fingerprinting — GENERATED by\n"
    "# scripts/sources_from_fingerprints.py. Do not hand-edit: rerun the script.\n"
    "#\n"
    "# Input: data/registry/fingerprints.jsonl (scripts/fingerprint_agencies.py).\n"
    "# Only strong matches on platforms this build can fetch appear here, and\n"
    "# only after each one was fetched once and answered.\n"
)


def load_fingerprints(path: Path) -> List[Dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def existing() -> tuple[set, set]:
    """(source ids, portal hosts) already configured, from every config file."""
    ids: set = set()
    hosts: set = set()
    for path in sorted(CONFIG_DIR.glob("sources*.yaml")):
        if path.resolve() == OUT.resolve():
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for cfg in data.get("sources") or []:
            if not isinstance(cfg, dict):
                continue
            if cfg.get("id"):
                ids.add(cfg["id"])
            for key in ("portal_url", "bonfire_host"):
                value = cfg.get(key)
                if value:
                    hosts.add(urlsplit(str(value)).netloc.lower() or str(value).lower())
    return ids, hosts


def _slug(entity_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", entity_id.lower()).strip("_")


def to_source(row: Dict) -> Optional[Dict]:
    adapter = PLATFORM_ADAPTERS.get(row["platform"])
    portal = row.get("portal_url") or row.get("checked_url")
    if not adapter or not portal:
        return None

    # Roster URLs are frequently http://, and the fingerprint records wherever
    # it actually landed. A configured source must not fetch a government bid
    # board in plaintext, so upgrade the scheme and let the probe decide: a host
    # that cannot serve https fails there and is dropped with a visible reason,
    # which is the right outcome either way.
    if portal.startswith("http://"):
        portal = "https://" + portal[len("http://"):]

    name = row["name"]
    cfg = {
        "id": f"fp_{_slug(row['entity_id'])}",
        "name": f"{name} ({row['platform'].title()})",
        "county": infer_county(name),
        "agency": name,
        "live_fetch": True,
        "adapter": adapter,
        "platform": row["platform"],
        "portal_url": portal,
    }
    if cfg["county"] not in COUNTY_NAMES:
        cfg["county"] = cfg["county"] or "unknown"

    if adapter == "bonfire":
        m = re.search(r"https?://([a-z0-9-]+)\.bonfirehub\.com", portal)
        if not m:
            return None
        cfg["bonfire_host"] = f"{m.group(1)}.bonfirehub.com"
    if adapter == "opengov":
        m = re.search(r"/portal/([a-z0-9_-]+)", portal)
        if not m:
            return None
        cfg["opengov_code"] = m.group(1)
    return cfg


def probe(candidates: List[Dict]) -> List[Dict]:
    """Fetch each candidate once; keep the ones that actually return a board.

    A signature proves the platform, not that the board is readable — a
    CivicPlus page that only links out to BidSync matches CivicPlus and returns
    nothing. Configuring it would report coverage that does not exist.
    """
    from src.sources.registry import ADAPTERS

    kept: List[Dict] = []
    for cfg in candidates:
        cls = ADAPTERS.get(cfg["adapter"])
        if cls is None:
            continue
        try:
            found = len(cls(cfg).fetch())
        except Exception as e:  # noqa: BLE001 — this is a probe report
            print(f"  drop {cfg['id']:<34} {type(e).__name__}: {str(e)[:44]}")
            continue
        print(f"  ok   {cfg['id']:<34} {found} open")
        kept.append(cfg)
    return kept


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fingerprints", type=Path, default=FINGERPRINTS)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--no-probe", action="store_true", help="skip the liveness probe")
    args = ap.parse_args()

    rows = load_fingerprints(args.fingerprints)
    if not rows:
        print(f"no fingerprints at {args.fingerprints} — run fingerprint_agencies.py first")
        return 1

    print(f"fingerprints: {len(rows)}")
    known_ids, known_hosts = existing()
    skipped: Counter = Counter()
    candidates: List[Dict] = []

    for row in rows:
        if row["platform"] == "unknown":
            skipped["unknown platform"] += 1
            continue
        if row.get("confidence") != "strong":
            skipped[f"{row['platform']} (weak match — a lead, not a tenant)"] += 1
            continue
        if row["platform"] not in PLATFORM_ADAPTERS:
            skipped[f"{row['platform']} (no adapter in this build)"] += 1
            continue

        cfg = to_source(row)
        if cfg is None:
            skipped[f"{row['platform']} (no usable portal URL)"] += 1
            continue
        if cfg["id"] in known_ids:
            skipped["already configured (id)"] += 1
            continue
        host = urlsplit(cfg["portal_url"]).netloc.lower()
        if host in known_hosts:
            skipped["already configured (host)"] += 1
            continue
        known_hosts.add(host)
        candidates.append(cfg)

    print(f"candidates on a platform we can fetch: {len(candidates)}")
    for reason, n in sorted(skipped.items(), key=lambda kv: -kv[1]):
        print(f"  skipped {n:>4}  {reason}")

    if candidates and not args.no_probe:
        print("\nprobing:")
        candidates = probe(candidates)
        print(f"  {len(candidates)} answered")

    if args.check:
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + yaml.safe_dump({"sources": candidates}, sort_keys=False, width=100),
        encoding="utf-8",
    )
    counties = {c["county"] for c in candidates if c["county"] in COUNTY_NAMES}
    print(f"\nWrote {len(candidates)} sources to {args.out}")
    print(f"  counties represented: {len(counties)}/67")
    print(f"  adapters: {dict(Counter(c['adapter'] for c in candidates))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
