#!/usr/bin/env python3
"""Turn fingerprint results into configured sources, for platforms we can fetch.

`scripts/fingerprint_agencies.py` answers "what does this agency run?".
This answers "so what?" — it takes the strong matches on platforms this build
has an adapter for and writes them as live sources.

Kept separate from the sweep on purpose. Discovering that a city runs CivicPlus
and deciding to crawl it every day are different decisions, and the second one
should be reviewable: this writes one generated file, prints what it skipped
and why, and can be re-run without touching anything a human tuned by hand.

Four rules the output depends on:

* **Strong matches only.** A weak fingerprint means the platform's name appeared
  in prose — usually "go register over there" — which is a lead, not a tenant.
  Configuring one would invent coverage.
* **Probe before configuring.** A signature on a page is not proof the adapter
  can read the board. Every candidate is fetched once, and only the ones that
  answer are written. This is where the CivicPlus pointer pages fall out.
* **Never shadow an existing source.** Anything already configured by hand or by
  another generator wins, matched on source id and on tenant.
* **The tenant is the identity, not the host.** CivicPlus and Bonfire give each
  agency its own hostname, so for them the two are the same thing. Jaggaer,
  VendorLink and BidNet put every agency in Florida behind one hostname, and
  matching prior art on the host alone meant that once Florida State was
  configured, every other university read as a duplicate — the University of
  Florida included, silently, with no line in the report to say so.

Usage::

    python scripts/sources_from_fingerprints.py --check     # report only
    python scripts/sources_from_fingerprints.py             # write the config
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional
from urllib.parse import urlsplit

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.fl_geo import COUNTY_NAMES, infer_county  # noqa: E402
from src.terms import GRANDFATHERED, may_build_adapter, verdict_for  # noqa: E402

FINGERPRINTS = Path("data/registry/fingerprints.jsonl")
OUT = Path("config/sources.fingerprinted.yaml")
CONFIG_DIR = Path("config")

#: Fingerprint platform -> (adapter, the config key naming the tenant, a regex
#: recovering that key from the portal URL). Only platforms in this map can
#: become sources; everything else is reported as an outstanding gap.
#:
#: The tenant key is what makes a shared-host platform configurable at all.
#: CivicPlus and Bonfire give each agency its own host, so the host *is* the
#: tenant; Jaggaer, VendorLink and BidNet put every agency in the state behind
#: one hostname, and without the key there is nothing to tell two of them apart.
PLATFORM_ADAPTERS: Dict[str, tuple] = {
    "civicplus": ("civicplus", None, None),
    "bonfire": ("bonfire", "bonfire_host", r"https?://([a-z0-9-]+\.bonfirehub\.com)"),
    "opengov": ("opengov", "opengov_code", r"/portal/([a-z0-9_-]+)"),
    "ionwave": ("ionwave", "ionwave_host", r"https?://([a-z0-9-]+\.ionwave\.net)"),
    "jaggaer": ("jaggaer", "jaggaer_org", r"[?&]CustomerOrg=([A-Za-z0-9_-]+)"),
    # Either host carries the tenant as its first label. The auth host is the
    # one fingerprints usually land on, and the one this must never configure —
    # see `_portal_for`.
    "workday_sourcing": (
        "workday_sourcing", "workday_tenant",
        r"https?://([a-z0-9-]+)\.(?:public-portal\.)?us\.workdayspend\.com",
    ),
}

#: Platforms with an adapter that this generator still leaves alone, and why.
#: Both have a dedicated discoverer that reads the platform's own agency list,
#: which yields the tenant key directly; a fingerprint lands on whatever page
#: the agency happened to link, and for these two that is almost never a URL
#: carrying the key. Measured: of 15 VendorLink fingerprints, *none* carried the
#: `a=` agency id — they point at login pages, home pages, an agency-named path,
#: and in one case a JavaScript file.
DISCOVERED_ELSEWHERE = {
    "vendorlink": "scripts/discover_vendorlink.py owns these — it reads the agency dropdown",
}

HEADER = (
    "# Florida sources discovered by fingerprinting — GENERATED by\n"
    "# scripts/sources_from_fingerprints.py. Do not hand-edit: rerun the script.\n"
    "#\n"
    "# Input: data/registry/fingerprints.jsonl (scripts/fingerprint_agencies.py).\n"
    "# Only strong matches on platforms this build can fetch appear here, and\n"
    "# only after each one was fetched once and answered.\n"
)


def load_fingerprints(path: Path) -> List[Dict]:
    """The current answer for each entity, not every answer ever recorded.

    The file is append-only — a recheck or a retry writes a new line rather
    than editing the old one — so reading it line by line would hand a stale
    verdict to the generator alongside the fresh one, and configure a source
    for a platform the agency has already left.
    """
    from src.pipeline.platform_watch import recorded

    return list(recorded(path).values())


#: Every config key that names a tenant, whatever platform it belongs to. A
#: hand-written source is claimed by its tenant the same way a generated one
#: is, or the two would not recognise each other.
_TENANT_KEYS = tuple(
    entry[1] for entry in PLATFORM_ADAPTERS.values() if entry[1]
) + ("vendorlink_agency", "vendor_registry_buyer")


def existing() -> tuple[set, set]:
    """(source ids, identities) already configured, from every config file.

    An identity is a host, or a host and a tenant where the platform has one —
    see `identity`. Both forms are recorded for a configured source, because a
    platform that gives each agency its own host is claimed by that host alone.
    """
    ids: set = set()
    claimed: set = set()
    for path in sorted(CONFIG_DIR.glob("sources*.yaml")):
        if path.resolve() == OUT.resolve():
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for cfg in data.get("sources") or []:
            if not isinstance(cfg, dict):
                continue
            if cfg.get("id"):
                ids.add(cfg["id"])
            tenants = [str(cfg[k]).lower() for k in _TENANT_KEYS if cfg.get(k)]
            for key in ("portal_url", "bonfire_host"):
                value = cfg.get(key)
                if not value:
                    continue
                host = urlsplit(str(value)).netloc.lower() or str(value).lower()
                # A shared-host platform is claimed per tenant; a one-host-per-
                # agency platform is claimed by the host. Recording both is what
                # lets one function answer for either.
                claimed.update(f"{host}#{t}" for t in tenants)
                if not tenants:
                    claimed.add(host)
    return ids, claimed


def _slug(entity_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", entity_id.lower()).strip("_")


def _portal_for(platform: str, tenant: str, portal: str) -> str:
    """The URL a configured source should carry, given its tenant.

    Only Workday needs rewriting, and it needs it badly:
    `<tenant>.us.workdayspend.com` is the authenticated supplier app and serves
    `Disallow: /`, while `<tenant>.public-portal.us.workdayspend.com` is the
    open board. A fingerprint almost always lands on the first — the agency
    links its registration page — and configuring that URL would point a
    crawler at a host we are not allowed to read.
    """
    if platform == "workday_sourcing":
        return f"https://{tenant}.public-portal.us.workdayspend.com/opportunities"
    return portal


def to_source(row: Dict) -> Optional[Dict]:
    entry = PLATFORM_ADAPTERS.get(row["platform"])
    portal = row.get("portal_url") or row.get("checked_url")
    if not entry or not portal:
        return None
    adapter, key, pattern = entry

    # Roster URLs are frequently http://, and the fingerprint records wherever
    # it actually landed. A configured source must not fetch a government bid
    # board in plaintext, so upgrade the scheme and let the probe decide: a host
    # that cannot serve https fails there and is dropped with a visible reason,
    # which is the right outcome either way.
    if portal.startswith("http://"):
        portal = "https://" + portal[len("http://"):]

    tenant = None
    if key is not None:
        m = re.search(pattern, portal, re.I)
        if not m:
            # The signature proved the platform; this URL does not name the
            # tenant. Nothing configurable, and inventing one would be a guess.
            return None
        tenant = m.group(1)
        portal = _portal_for(row["platform"], tenant, portal)

    name = row["name"]
    cfg = {
        "id": f"fp_{_slug(row['entity_id'])}",
        "name": f"{name} ({row['platform'].title()})",
        "county": infer_county(name),
        "agency": name,
        "live_fetch": True,
        "adapter": adapter,
        "platform": row["platform"],
        "portal_url": portal,
    }
    if cfg["county"] not in COUNTY_NAMES:
        cfg["county"] = cfg["county"] or "unknown"
    if key is not None:
        cfg[key] = tenant
    return cfg


def identity(cfg: Dict) -> str:
    """What makes this source the same source as one already configured.

    The host alone is wrong, and wrong in the direction that hides work. Every
    Jaggaer tenant in Florida lives on `bids.sciquest.com`, so once one
    university was configured, matching on host silently dropped every other
    one as "already configured" — the University of Florida included. Where a
    platform names its tenant, the tenant is the identity.
    """
    entry = PLATFORM_ADAPTERS.get(cfg.get("platform") or "")
    key = entry[1] if entry else None
    host = urlsplit(cfg["portal_url"]).netloc.lower()
    if key and cfg.get(key):
        return f"{host}#{str(cfg[key]).lower()}"
    return host


def probe(candidates: List[Dict]) -> List[Dict]:
    """Fetch each candidate once; keep the ones that actually return a board.

    A signature proves the platform, not that the board is readable — a
    CivicPlus page that only links out to BidSync matches CivicPlus and returns
    nothing. Configuring it would report coverage that does not exist.
    """
    from src.sources.registry import ADAPTERS

    kept: List[Dict] = []
    for cfg in candidates:
        cls = ADAPTERS.get(cfg["adapter"])
        if cls is None:
            continue
        try:
            found = len(cls(cfg).fetch())
        except Exception as e:  # noqa: BLE001 — this is a probe report
            print(f"  drop {cfg['id']:<34} {type(e).__name__}: {str(e)[:44]}")
            continue
        print(f"  ok   {cfg['id']:<34} {found} open")
        kept.append(cfg)
    return kept


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fingerprints", type=Path, default=FINGERPRINTS)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    ap.add_argument("--no-probe", action="store_true", help="skip the liveness probe")
    args = ap.parse_args()

    rows = load_fingerprints(args.fingerprints)
    if not rows:
        print(f"no fingerprints at {args.fingerprints} — run fingerprint_agencies.py first")
        return 1

    print(f"fingerprints: {len(rows)}")
    known_ids, known_hosts = existing()  # ids and identities — see `identity`
    skipped: Counter = Counter()
    candidates: List[Dict] = []

    for row in rows:
        if row["platform"] == "unknown":
            skipped["unknown platform"] += 1
            continue
        if row["platform"] == "selfhosted":
            # A real, readable board with no platform behind it. Not a weak
            # match and not a miss — it is waiting on a page-level reader, and
            # no adapter in this build will ever fit it.
            skipped["selfhosted (their own page — needs a reader, not an adapter)"] += 1
            continue
        if row.get("confidence") != "strong":
            skipped[f"{row['platform']} (weak match — a lead, not a tenant)"] += 1
            continue
        if row["platform"] in DISCOVERED_ELSEWHERE:
            skipped[f"{row['platform']} ({DISCOVERED_ELSEWHERE[row['platform']]})"] += 1
            continue
        if not may_build_adapter(row["platform"]) and row["platform"] not in GRANDFATHERED:
            # The terms decide, not the endpoint. `src/terms.py` carries the
            # verdict and the clause behind it; a platform that forbids reading
            # never becomes a configured source, however easy it looks. This is
            # the second route into the fetcher — an adapter is the first — and
            # 36 DemandStar fingerprints sit in the registry waiting for it.
            verdict = verdict_for(row["platform"])
            reason = verdict.status if verdict else "no recorded terms verdict"
            skipped[f"{row['platform']} (terms: {reason})"] += 1
            continue
        if row["platform"] not in PLATFORM_ADAPTERS:
            skipped[f"{row['platform']} (no adapter in this build)"] += 1
            continue

        cfg = to_source(row)
        if cfg is None:
            skipped[f"{row['platform']} (the URL does not name the tenant)"] += 1
            continue
        if cfg["id"] in known_ids:
            skipped["already configured (id)"] += 1
            continue
        who = identity(cfg)
        if who in known_hosts:
            skipped["already configured (same tenant)"] += 1
            continue
        known_hosts.add(who)
        candidates.append(cfg)

    print(f"candidates on a platform we can fetch: {len(candidates)}")
    for reason, n in sorted(skipped.items(), key=lambda kv: -kv[1]):
        print(f"  skipped {n:>4}  {reason}")

    if candidates and not args.no_probe:
        print("\nprobing:")
        candidates = probe(candidates)
        print(f"  {len(candidates)} answered")

    if args.check:
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        HEADER + yaml.safe_dump({"sources": candidates}, sort_keys=False, width=100),
        encoding="utf-8",
    )
    counties = {c["county"] for c in candidates if c["county"] in COUNTY_NAMES}
    print(f"\nWrote {len(candidates)} sources to {args.out}")
    print(f"  counties represented: {len(counties)}/67")
    print(f"  adapters: {dict(Counter(c['adapter'] for c in candidates))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
