[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#04719E"
backgroundColor = "#F8F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"
